version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.8
    - 13.0.9
